name: xcdskd
channels:
  - conda-forge
  - matsci
  - defaults
dependencies:
  - attrs
  - babel
  - ca-certificates
  - cffi
  - cloudpickle
  - colorama
  - colorcet
  - conda
  - conda-env
  - h5py
  - hdf5
  - jupyter
  - jupyterlab
  - matplotlib
  - nbconvert
  - nbformat
  - notebook
  - numba
  - numpy
  - numpydoc
  - pandoc
  - pandocfilters
  - pillow
  - pip
  - psutil
  - pygments
  - pylint
  - pytest
  - python=3.8
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - six
  - snappy
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-websupport
  - sympy
  - wheel
  - pymatgen
  - spglib
  - pip
  - transforms3d
  - pip:
    - autopep8
    - mako
    - matplotlib-scalebar
    - moderngl
    - msgpack
    - nbsphinx
    - nlopt
    - opencv-python
    - sphinx-rtd-theme
    - tables
    - tifffile
    - tqdm
    
