channels:
  - conda-forge
dependencies:
  - python=3.6
  - sphinx=2.1.2
  - pandoc
  - nbconvert
  - ipykernel
  - pip:
    - git+https://github.com/spatialaudio/nbsphinx.git@master
    - sphinx_rtd_theme
    - numpydoc

