channels:
  - conda-forge
dependencies:
  - python=3.6
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - numpy
  - win32api
  - matplotlib
  - pip:
    - git+https://github.com/spatialaudio/nbsphinx.git@master
    - sphinx_rtd_theme
    - numpydoc